config/routes.rb
Simplebudget::Application.routes.draw do

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
  resources :budgets, :shallow => true do
    resources :transactions
  end
  

end

app/models/budget.rb
class Budget
  include Mongoid::Document
  has_and_belongs_to_many :users
  embeds_many :transactions
  field :name, type: String
  field :daily_amount, type: Integer # cents
  validates_numericality_of :daily_amount, greater_than: 0, only_integer: true
  before_create :convert_dollars_to_cents

  def self.money_format(cents)
    cs = cents.to_s
    dollars = cs[0..-3]
    dollars = '0' if dollars.nil? or dollars == ''
    c = cs[-2..-1]
    c = "0#{cs}" if c.nil?
    "$#{dollars}.#{c}"
  end

  protected

  def convert_dollars_to_cents
    self.daily_amount = daily_amount * 100 unless daily_amount.nil?
  end

end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  embedded_in :budget
  field :amount, type: Integer # cents
  field :description, type: String
  field :when, type: DateTime
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :budgets
  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @budgets = current_user.budgets
  end
  
  def new
    @budget = Budget.new
  end
  
  def create
    begin
      current_user.budgets.create! params[:budget]
      redirect_to budgets_path
    rescue Mongoid::Errors::Validations => e
      flash[:notice] = e.message
      redirect_to new_budget_path
    end
  end
  
  def show
    begin
      @budget = current_user.budgets.find params[:id]
    rescue Mongoid::Errors::DocumentNotFound => e
      flash[:notice] = 'unknown budget'
      redirect_to budgets_path
    end
  end
  
  def edit
    show
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @transactions = Transaction.find
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_form.html.haml
= form_for @budget do |f|
  %fieldset
    %div= f.label :name, 'name'
    %div= f.text_field :name
    %div= f.label :daily_amount, 'daily amount'
    %div= f.text_field :daily_amount, value: Budget.money_format(@budget.daily_amount)
    %div= f.submit

app/views/budgets/edit.html.haml
%h2 edit budget
= render 'budgets/form'

app/views/budgets/index.html.haml
%h2 budgets
- if @budgets.empty?
  %p none yet
- else
  %ul
    - @budgets.each do |budget|
      %li= link_to budget.name, edit_budget_path(budget)
%p= link_to 'new', new_budget_path
  

app/views/budgets/new.html.haml
%h2 new budget
= render 'budgets/form'

app/views/budgets/show.html.haml
%h2= "#{@budget.name} budget"
%p= Budget.money_format @budget.daily_amount

app/views/home/index.html.haml
%h2 welcome

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title simple budget
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body{:class => params[:controller]}
    #container.container
      %header
        %h1 simple budget
        %nav
          %ul.hmenu
            = render 'shared/navigation'
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String)
      #main{:role => "main"}
        = yield
      %footer

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li= link_to 'budgets', budgets_path
  %li= link_to 'logout', destroy_user_session_path, :method => :delete
  %li= link_to 'edit account', edit_user_registration_path
- else
  %li= link_to 'login', new_user_session_path
  %li= link_to 'sign up', new_user_registration_path

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}